### ISSUE TITLE
Support Translations keys with only one language

### ISSUE THREAD

**Issue by westonganger** [electric-feel/i18n-backend-side_by_side#7]
If a project currently only has one translation but is starting to add more it might be beneficial to be able to support the following addition:

```yaml
_:
  common:
    welcome:
      _en: Welcome
      _es: Bienvenido
      _de: Willkommen
    subject: Subject ### Interpret this line as the default locale or for all locales
```
